### ISSUE TITLE
Domains error

### ISSUE THREAD

**Issue by PyWhy-3275** [fruithost/Modules#22]
```
[Sun Dec 17 06:10:07.079089 2023] [proxy_fcgi:error] [pid 41882] [client 82.147.93.148:0] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'fruithost.fh_domains' doesn't exist in /etc/fruithost/panel/classes/Storage/DatabaseFactory.class.php:73
	Stack trace:
	#0 /etc/fruithost/panel/classes/Storage/DatabaseFactory.class.php(73): PDOStatement->execute(Array)
	#1 /etc/fruithost/panel/classes/Storage/DatabaseFactory.class.php(88): fruithost\\Storage\\DatabaseFactory->query('SELECT * FROM `...', NULL, Array)
	#2 /etc/fruithost/panel/classes/Storage/Database.class.php(30): fruithost\\Storage\\DatabaseFactory->fetch('SELECT * FROM `...', Array)
	#3 /etc/fruithost/modules/domains/module.php(18): fruithost\\Storage\\Database::fetch('SELECT * FROM `...', Array)
	#4 /etc/fruithost/panel/classes/Modules/ModuleInterface.class.php(18): Domains->init()
	#5 [internal function]: fruithost\\Modules\\ModuleInterface->__construct(Object(fruithost\\System\\Core), Object(fruithost\\Modules\\Module))
	#6 /etc/fruithost/panel/classes/Modules/Module.class.php(120): R...', referer: https://****/admin/modules?enable=domains
```

**Comment by Bizarrus** [comment]
You must install the module, before you enable it:
```
fruithost install domains
```

https://github.com/fruithost/Documentation/tree/main

**Comment by PyWhy-3275** [comment]
The installation and activation was done via the console

![image](https://github.com/fruithost/Modules/assets/24767863/5a93be66-dc7c-40f2-9744-d41d557846bb)

**Comment by Bizarrus** [comment]
Are you sure, that you had install the service correctly?
It seems, that the PHP-FPM process is not responding. Are you sure, that you have installed `PHP 8.2 FPM`? Which OS you have installed?

**Comment by PyWhy-3275** [comment]
Debian 11

**Comment by Bizarrus** [comment]
Which PHP-FPM Version do you have installed? These informations still missing.

Currently only 8.2 is supported.

**Comment by PyWhy-3275** [comment]
8.2

**Comment by Bizarrus** [comment]
Check if the path is available on your system: `/run/php/php8.2-fpm.sock`

**Comment by PyWhy-3275** [comment]
sec, checks

**Comment by PyWhy-3275** [comment]
![image](https://github.com/fruithost/Modules/assets/24767863/f429be52-9494-4c42-a688-d466e68cfa58)

**Comment by PyWhy-3275** [comment]
I even reinstalled php for this to make sure that I didn't make a mistake somewhere, but it didn't help

**Comment by Bizarrus** [comment]
Can you debug the PHP.class.php with print the contents? I want to see the output of these

**Comment by PyWhy-3275** [comment]
if you tell me what needs to be done for this, exactly

**Comment by Bizarrus** [comment]
Add at the `execute` method an `var_dump` like these:
```php
$this->content = $result;

var_dump($this->content);
```
https://github.com/fruithost/Panel/blob/b7a3c019f9cabaf26bb8adcec412a366b88838f4/classes/Services/PHP.class.php#L59

**Comment by PyWhy-3275** [comment]
string(27) "sh: 1: cgi-fcgi: not found
"
PHP Warning:  Undefined array key 1 in /etc/fruithost/panel/classes/Services/PHP.class.php on line 24

**Comment by Bizarrus** [comment]
Okay, you can revert the Changes.

An installations package is missing, that provides `cgi-fcgi`. Wait a minute, i will search the manual installation for you

**Comment by PyWhy-3275** [comment]
Now it's clear why it didn't work...
I've already found it.
It's not there, so it's in the auto installer

**Comment by Bizarrus** [comment]
Okay, already solved the issue?

I will create later an fallback with better error messaging.

**Comment by PyWhy-3275** [comment]
Yes, thx
