### ISSUE TITLE
[domains] no config

### ISSUE THREAD

**Issue by PyWhy-3275** [fruithost/Modules#30]
After creating the domain, only the folder appears, but the config does not appear
![image](https://github.com/fruithost/Modules/assets/24767863/de7af989-1b6a-4362-89cc-7f318f0e8e74)
![image](https://github.com/fruithost/Modules/assets/24767863/b2f36aab-57a0-40b7-8477-a9ddaf341162)

**Comment by Bizarrus** [comment]
I will update the permissions of the module in few minutes.

We had an permissions update (See Issue #4), the domain module was not changed after the update.

You can solve the problem yourself by editing the following file:
`/etc/fruithost/modules/domains/daemon.php`

Put over the `<?php` follwing line:
```php
#!fruithost:permissions:root
<?php
```

**Comment by PyWhy-3275** [comment]
I'll try it now

**Comment by PyWhy-3275** [comment]
Hmm, it didn't help if I understood you correctly, what should be added at the very top

**Comment by Bizarrus** [comment]
Please execute `fruithost daemon`, any errors appears?

**Comment by PyWhy-3275** [comment]
```root@my:~# fruithost daemon
Running Daemon...
Fixing System-Paths
Fixing User-Paths
Call Modules...
Enabled Modules: 9
Modules will be deinstalled: 0
- Skip ftp (No Daemon)
+ Run protected-directorys
+ Run cronjob
+ Run domains
#!fruithost:permissions:root
- Ignore modules.packages (Disabled)
- Skip faq (No Daemon)
- Ignore php (Disabled)
+ Run ssl
- Ignore theme (Disabled)
Done.
```

**Comment by Bizarrus** [comment]
Apparently you have not inserted the line correctly. The following output should appear:
```
+ Run node [executed as ROOT]
```

**Comment by PyWhy-3275** [comment]
![image](https://github.com/fruithost/Modules/assets/24767863/478e4ee3-bba3-45f6-9593-2bbe9479e555)

**Comment by Bizarrus** [comment]
That is correct. Are hidden chars perhaps set at the end of the line? Is the line feed correct (Windows usually uses `\r\n` for Linux, however, `\n` is used)?

Ich habe das Update bereits hochgeladen (#4db53bc).

**Comment by PyWhy-3275** [comment]
it was edited via nano, I just closed the console and showed it via sftp

**Comment by Bizarrus** [comment]
I will install Debian 11 right away and try to reproduce this. Debian 12 (bookworm) is currently recommended.

**Comment by PyWhy-3275** [comment]
even ssl is the same `+ Run ssl #!fruithost:permissions:root`

**Comment by Bizarrus** [comment]
Can you update the binary daemon and try this again?

**Comment by PyWhy-3275** [comment]
its work, thx

**Comment by PyWhy-3275** [comment]
Only index.html empty

**Comment by PyWhy-3275** [comment]
:(
